export const mockProducts = [
  {
    id: 1,
    sku: "netflix-premium",
    title: "Netflix Premium Account",
    description: `<p>​<span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">Boost your DC Server to lvl 3 with x14 boost for 3 month (full warranty &amp; revoke warranty too)</span></p>

<p><span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">Delivery process:</span></p>

<p><span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">-&gt; Send me the server you want to activate the 14 boosts on. ( permanent invite link)</span></p>

<p><span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">-&gt; After placing the order you will get your x14 boost in ¡¡LESS THAN 10 MINUTES!!</span></p>

<p><span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">-&gt; Once we process your order, we will boost automatically (no action required from your side).</span></p>

<p><span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">-&gt; Order with us for a hassle-free process.</span></p>

<p><span style="color: rgb(48, 48, 48);font-size: 14px;background-color: rgb(250, 250, 252)">-&gt; Note: DO NOT REMOVE the booster IDs from your server. If you kick or ban them, the guarantee will be void, and we will not be able to restore your boosts, it will be your loss.</span>​<br>
</p>`,
    image: "https://s6.imgcdn.dev/YcxY9N.png",
    cardColor: "#E50914",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Giải trí",
      slug: "giai-tri",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [
      {
        id: 1,
        retailPrice: 95000,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 50 },
        attributeSet: { value: "1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 2,
        retailPrice: 240000,
        attributeSetHash: "duration:3months",
        inventory: { quantity: 30 },
        attributeSet: { value: "3 Tháng", unit: "months" },
        attributeName: "3 Months Plan",
      },
      {
        id: 3,
        retailPrice: 470000,
        attributeSetHash: "duration:6months",
        inventory: { quantity: 30 },
        attributeSet: { value: "6 Tháng", unit: "months" },
        attributeName: "6 Months Plan",
      },
      {
        id: 4,
        retailPrice: 820000,
        attributeSetHash: "duration:12months",
        inventory: { quantity: 30 },
        attributeSet: { value: "12 Tháng", unit: "months" },
        attributeName: "12 Months Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 12.99,
    lowestSalePrice: 12.99,
  },
  {
    id: 2,
    sku: "spotify-premium",
    title: "Spotify Premium",
    description: "Ad-free music streaming with unlimited skips, offline downloads, and high-quality audio.",
    image: "https://s6.imgcdn.dev/Ycx9Rv.png",
    cardColor: "#1DB954",
    keywords: "spotify, music, premium, streaming, ad-free",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-06-08"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Giải trí",
      slug: "giai-tri",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [
      {
        id: 1,
        retailPrice: 55000,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 100 },
        attributeSet: { value: "1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 2,
        retailPrice: 140000,
        attributeSetHash: "duration:3months",
        inventory: { quantity: 75 },
        attributeSet: { value: "3 Tháng", unit: "months" },
        attributeName: "3 Months Plan",
      },
      {
        id: 3,
        retailPrice: 400000,
        attributeSetHash: "duration:12months",
        inventory: { quantity: 75 },
        attributeSet: { value: "12 Tháng", unit: "months" },
        attributeName: "3 Months Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 7.99,
    lowestSalePrice: 7.99,
  },
  {
    id: 4,
    sku: "youtube-premium",
    title: "Youtube Premium",
    description: "Professional design tools with premium templates, background remover, and brand kit features.",
    image: "/images/products/youtube.png",
    cardColor: "#00C4CC",
    keywords: "canva, design, pro, templates, graphics",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-06-03"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 1,
        retailPrice: 70000,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 80 },
        attributeSet: { value: "1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 2,
        retailPrice: 195000,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 25 },
        attributeSet: { value: "3 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 3,
        retailPrice: 220000,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 25 },
        attributeSet: { value: "6 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 4,
        retailPrice: 380000,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 25 },
        attributeSet: { value: "12 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 9.99,
    lowestSalePrice: 9.99,
  },
  {
    id: 5,
    sku: "chatgpt-plus",
    title: "ChatGPT Plus",
    description:
      "Complete Adobe Creative Suite including Photoshop, Illustrator, Premiere Pro, and more professional tools.",
    image: "/images/products/GPT.png",
    cardColor: "#FF0000",
    keywords: "adobe, creative cloud, photoshop, design, video editing",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-06-01"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 9,
        retailPrice: 120000,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 40 },
        attributeSet: { value: "1 Tháng (Dùng chung)", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 10,
        retailPrice: 440000,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 15 },
        attributeSet: { value: "1 Tháng (Nâng cấp trực tiếp)", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 45.99,
    lowestSalePrice: 45.99,
  },
  {
    id: 6,
    sku: "apple-music",
    title: "Apple Music",
    description: "In-game currency for Valorant to purchase weapon skins, agents, and battle passes.",
    image: "/images/products/apple-music.png",
    cardColor: "#FF4654",
    keywords: "valorant, points, gaming, riot games, fps",
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-05-30"),
    categoryId: 2,
    supplierId: 2,
    category: {
      id: 2,
      name: "Gaming & Social",
      slug: "gaming-social",
    },
    supplier: {
      id: 2,
      name: "Gaming Services Ltd.",
    },
    properties: [
      {
        id: 11,
        retailPrice: 300000,
        salePrice: null,
        attributeSetHash: "amount:475vp",
        inventory: { quantity: 500 },
        attributeSet: { value: "6 Tháng", unit: "VP" },
        attributeName: "475 VP",
      },
      {
        id: 12,
        retailPrice: 360000,
        salePrice: null,
        attributeSetHash: "amount:1000vp",
        inventory: { quantity: 300 },
        attributeSet: { value: "12 Tháng", unit: "VP" },
        attributeName: "1000 VP",
      },
    ],
    isAvailable: true,
    lowestPrice: 4.99,
    lowestSalePrice: 8.99,
  },
  {
    id: 7,
    sku: "bumble",
    title: "Bumble",
    description: "Ad-free YouTube experience with background play, offline downloads, and YouTube Music included.",
    image: "/images/products/bumble.png",
    cardColor: "#FF0000",
    keywords: "youtube, premium, ad-free, music, video",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-05-28"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [
      {
        id: 14,
        retailPrice: 300000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 120 },
        attributeSet: { value: "3 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 15,
        retailPrice: 390000,
        salePrice: null,
        attributeSetHash: "type:family",
        inventory: { quantity: 60 },
        attributeSet: { value: "6 Tháng", unit: "" },
        attributeName: "Family Plan (6 members)",
      },
      {
        id: 17,
        retailPrice: 730000,
        salePrice: null,
        attributeSetHash: "type:family",
        inventory: { quantity: 60 },
        attributeSet: { value: "12 Tháng", unit: "" },
        attributeName: "Family Plan (6 members)",
      },
    ],
    isAvailable: true,
    lowestPrice: 9.99,
    lowestSalePrice: 9.99,
  },
  {
    id: 8,
    sku: "k-cong",
    title: "K+",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/k+.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 520000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "3 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 17,
        retailPrice: 780000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "6 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 18,
        retailPrice: 1150000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "12 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "tinder",
    title: "Tinder",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/tinder.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 390000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "Gold - 6 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 17,
        retailPrice: 480000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "Platinum - 6 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "autocad",
    title: "Autocad",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/autocad.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 210000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "12 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "figma",
    title: "Figma",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/figma.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 230000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "grammarly",
    title: "Grammarly",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/grammarly.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 220000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 17,
        retailPrice: 330000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "3 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 18,
        retailPrice: 410000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "6 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "jetbrains",
    title: "Jetbrains",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/jetbrains.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 370000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "Edu - 12 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "notion",
    title: "Notion",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/notion.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 300000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "Business, có AI - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 17,
        retailPrice: 1600000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "Business, có AI - 12 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 18,
        retailPrice: 210000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "Business, Không AI - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 19,
        retailPrice: 1100000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "Business, Không AI - 12 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 20,
        retailPrice: 220000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "Plus, có AI - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 21,
        retailPrice: 730000,
        salePrice: null,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "Plus, có AI - 12 Tháng", unit: "year" },
        attributeName: "1 Year Plan",
      },
      {
        id: 22,
        retailPrice: 130000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "Plus, Không AI - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
  {
    id: 8,
    sku: "zoom",
    title: "Zoom",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "/images/products/zoom.png",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 130000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "100 Mem - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 18,
        retailPrice: 230000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "100 Mem - 3 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 19,
        retailPrice: 390000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "100 Mem - 6 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 17,
        retailPrice: 610000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "100 Mem - 12 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 20,
        retailPrice: 2000000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1000 Mem - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 21,
        retailPrice: 5610000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1000 Mem - 3 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 22,
        retailPrice: 10900000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1000 Mem - 6 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 23,
        retailPrice: 20300000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1000 Mem - 12 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 24,
        retailPrice: 380000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "300 Mem - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 25,
        retailPrice: 850000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "300 Mem - 3 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 26,
        retailPrice: 1400000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "300 Mem - 6 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 27,
        retailPrice: 2300000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "300 Mem - 12 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 28,
        retailPrice: 1400000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "500 Mem - 1 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 29,
        retailPrice: 3700000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "500 Mem - 3 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 30,
        retailPrice: 6830000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "500 Mem - 6 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 31,
        retailPrice: 12850000,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "500 Mem - 12 Tháng", unit: "month" },
        attributeName: "1 Month Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
];

export const bestSellingProducts = [
  {
    id: 1,
    sku: "netflix-premium",
    title: "Netflix Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/netflix.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 95000,
  },
  {
    id: 2,
    sku: "spotify-premium",
    title: "Spotify Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/spotify.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 85000,
  },
  {
    id: 3,
    sku: "youtube-premium",
    title: "Youtube Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/youtube.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 85000,
  },
  {
    id: 3,
    sku: "chatgpt-plus",
    title: "Chat GPT Plus",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/GPT.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 120000,
  },
];

export const entertainmentProducts = [
  {
    id: 3,
    sku: "apple-music",
    title: "Apple Music",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/apple-music.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 300000,
  },
  {
    id: 3,
    sku: "bumble",
    title: "Bumble",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/bumble.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 300000,
  },
  {
    id: 3,
    sku: "k-cong",
    title: "K+",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/k+.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 520000,
  },
  {
    id: 1,
    sku: "netflix-premium",
    title: "Netflix Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/netflix.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 95000,
  },
  {
    id: 2,
    sku: "spotify-premium",
    title: "Spotify Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/spotify.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 85000,
  },
  {
    id: 3,
    sku: "tinder",
    title: "Tinder",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/tinder.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 390000,
  },
  {
    id: 3,
    sku: "youtube-premium",
    title: "Youtube Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/youtube.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 85000,
  },
];

export const workingProducts = [
  {
    id: 3,
    sku: "autocad",
    title: "Autocad",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/autocad.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 210000,
  },
  {
    id: 3,
    sku: "figma",
    title: "Figma",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/figma.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 230000,
  },
  {
    id: 3,
    sku: "grammarly",
    title: "Grammarly",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/grammarly.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 220000,
  },
  {
    id: 3,
    sku: "jetbrains",
    title: "Jetbrains",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/jetbrains.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 370000,
  },
  {
    id: 3,
    sku: "notion",
    title: "Notion",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/notion.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 130000,
  },
  {
    id: 3,
    sku: "zoom",
    title: "Zoom",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/zoom.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 130000,
  },
];

export const aiProducts = [
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Chat GPT Plus",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/GPT.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 120000,
  },
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Copilot",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/copilot.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 90000,
  },
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Grok",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/grok.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 420000,
  },
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Perplexity",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/perplexity.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 100000,
  },
];

export const eduProducts = [
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Canva",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/canva.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 60000,
  },
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Coursera",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/coursera.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 190000,
  },
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Doulingo Super",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/doulingo-super.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 190000,
  },
  {
    id: 3,
    sku: "NETFLIX-PREMIUM",
    title: "Elsa Premium",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "/images/products/elsa.png",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [],
    isAvailable: true,
    lowestPrice: 450000,
  },
];
