export const mockProducts = [
  {
    id: 1,
    sku: "NETFLIX-PREMIUM",
    title: "Netflix Premium Account",
    description:
      "Premium Netflix account with 4K streaming, multiple devices support, and offline downloads. Valid for 1 month.",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400",
    cardColor: "#E50914",
    keywords: "netflix, streaming, premium, 4k, entertainment",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [
      {
        id: 1,
        retailPrice: 15.99,
        salePrice: 12.99,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 50 },
        attributeSet: { value: "1 Month", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 2,
        retailPrice: 45.99,
        salePrice: 39.99,
        attributeSetHash: "duration:3months",
        inventory: { quantity: 30 },
        attributeSet: { value: "3 Months", unit: "months" },
        attributeName: "3 Months Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 12.99,
    lowestSalePrice: 12.99,
  },
  {
    id: 2,
    sku: "SPOTIFY-PREMIUM",
    title: "Spotify Premium Account",
    description: "Ad-free music streaming with unlimited skips, offline downloads, and high-quality audio.",
    image: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400",
    cardColor: "#1DB954",
    keywords: "spotify, music, premium, streaming, ad-free",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-06-08"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [
      {
        id: 3,
        retailPrice: 9.99,
        salePrice: 7.99,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 100 },
        attributeSet: { value: "1 Month", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 4,
        retailPrice: 29.99,
        salePrice: null,
        attributeSetHash: "duration:3months",
        inventory: { quantity: 75 },
        attributeSet: { value: "3 Months", unit: "months" },
        attributeName: "3 Months Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 7.99,
    lowestSalePrice: 7.99,
  },
  {
    id: 3,
    sku: "DISCORD-NITRO",
    title: "Discord Nitro",
    description: "Enhanced Discord experience with custom emojis, larger file uploads, HD video, and server boosts.",
    image: "https://images.unsplash.com/photo-1614680376573-df3480f6c158?w=400",
    cardColor: "#5865F2",
    keywords: "discord, nitro, gaming, communication, chat",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-06-05"),
    categoryId: 2,
    supplierId: 2,
    category: {
      id: 2,
      name: "Gaming & Social",
      slug: "gaming-social",
    },
    supplier: {
      id: 2,
      name: "Gaming Services Ltd.",
    },
    properties: [
      {
        id: 5,
        retailPrice: 9.99,
        salePrice: 8.99,
        attributeSetHash: "type:nitro-basic",
        inventory: { quantity: 200 },
        attributeSet: { value: "Nitro Basic", unit: "" },
        attributeName: "Nitro Basic",
      },
      {
        id: 6,
        retailPrice: 14.99,
        salePrice: 12.99,
        attributeSetHash: "type:nitro-premium",
        inventory: { quantity: 150 },
        attributeSet: { value: "Nitro Premium", unit: "" },
        attributeName: "Nitro Premium",
      },
    ],
    isAvailable: true,
    lowestPrice: 8.99,
    lowestSalePrice: 8.99,
  },
  {
    id: 4,
    sku: "CANVA-PRO",
    title: "Canva Pro Account",
    description: "Professional design tools with premium templates, background remover, and brand kit features.",
    image: "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400",
    cardColor: "#00C4CC",
    keywords: "canva, design, pro, templates, graphics",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-06-03"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 7,
        retailPrice: 12.99,
        salePrice: 9.99,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 80 },
        attributeSet: { value: "1 Month", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 8,
        retailPrice: 119.99,
        salePrice: 99.99,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 25 },
        attributeSet: { value: "1 Year", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 9.99,
    lowestSalePrice: 9.99,
  },
  {
    id: 5,
    sku: "ADOBE-CC",
    title: "Adobe Creative Cloud",
    description:
      "Complete Adobe Creative Suite including Photoshop, Illustrator, Premiere Pro, and more professional tools.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400",
    cardColor: "#FF0000",
    keywords: "adobe, creative cloud, photoshop, design, video editing",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-06-01"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 9,
        retailPrice: 52.99,
        salePrice: 45.99,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 40 },
        attributeSet: { value: "1 Month", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 10,
        retailPrice: 599.88,
        salePrice: 499.99,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 15 },
        attributeSet: { value: "1 Year", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: true,
    lowestPrice: 45.99,
    lowestSalePrice: 45.99,
  },
  {
    id: 6,
    sku: "VALORANT-POINTS",
    title: "Valorant Points",
    description: "In-game currency for Valorant to purchase weapon skins, agents, and battle passes.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400",
    cardColor: "#FF4654",
    keywords: "valorant, points, gaming, riot games, fps",
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-05-30"),
    categoryId: 2,
    supplierId: 2,
    category: {
      id: 2,
      name: "Gaming & Social",
      slug: "gaming-social",
    },
    supplier: {
      id: 2,
      name: "Gaming Services Ltd.",
    },
    properties: [
      {
        id: 11,
        retailPrice: 4.99,
        salePrice: null,
        attributeSetHash: "amount:475vp",
        inventory: { quantity: 500 },
        attributeSet: { value: "475", unit: "VP" },
        attributeName: "475 VP",
      },
      {
        id: 12,
        retailPrice: 9.99,
        salePrice: 8.99,
        attributeSetHash: "amount:1000vp",
        inventory: { quantity: 300 },
        attributeSet: { value: "1000", unit: "VP" },
        attributeName: "1000 VP",
      },
      {
        id: 13,
        retailPrice: 19.99,
        salePrice: 17.99,
        attributeSetHash: "amount:2050vp",
        inventory: { quantity: 200 },
        attributeSet: { value: "2050", unit: "VP" },
        attributeName: "2050 VP",
      },
    ],
    isAvailable: true,
    lowestPrice: 4.99,
    lowestSalePrice: 8.99,
  },
  {
    id: 7,
    sku: "YOUTUBE-PREMIUM",
    title: "YouTube Premium",
    description: "Ad-free YouTube experience with background play, offline downloads, and YouTube Music included.",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400",
    cardColor: "#FF0000",
    keywords: "youtube, premium, ad-free, music, video",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-05-28"),
    categoryId: 1,
    supplierId: 1,
    category: {
      id: 1,
      name: "Streaming Services",
      slug: "streaming-services",
    },
    supplier: {
      id: 1,
      name: "Digital Entertainment Co.",
    },
    properties: [
      {
        id: 14,
        retailPrice: 11.99,
        salePrice: 9.99,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 120 },
        attributeSet: { value: "1 Month", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 15,
        retailPrice: 17.99,
        salePrice: 14.99,
        attributeSetHash: "type:family",
        inventory: { quantity: 60 },
        attributeSet: { value: "Family Plan", unit: "" },
        attributeName: "Family Plan (6 members)",
      },
    ],
    isAvailable: true,
    lowestPrice: 9.99,
    lowestSalePrice: 9.99,
  },
  {
    id: 8,
    sku: "NOTION-PRO",
    title: "Notion Pro Workspace",
    description: "All-in-one workspace for notes, tasks, wikis, and databases with unlimited blocks and file uploads.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400",
    cardColor: "#000000",
    keywords: "notion, productivity, workspace, notes, organization",
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-05-25"),
    categoryId: 3,
    supplierId: 3,
    category: {
      id: 3,
      name: "Design & Productivity",
      slug: "design-productivity",
    },
    supplier: {
      id: 3,
      name: "Creative Tools Inc.",
    },
    properties: [
      {
        id: 16,
        retailPrice: 8.0,
        salePrice: null,
        attributeSetHash: "duration:1month",
        inventory: { quantity: 0 },
        attributeSet: { value: "1 Month", unit: "month" },
        attributeName: "1 Month Plan",
      },
      {
        id: 17,
        retailPrice: 96.0,
        salePrice: 79.99,
        attributeSetHash: "duration:1year",
        inventory: { quantity: 35 },
        attributeSet: { value: "1 Year", unit: "year" },
        attributeName: "1 Year Plan",
      },
    ],
    isAvailable: false, // Out of stock for monthly plan
    lowestPrice: 79.99,
    lowestSalePrice: 79.99,
  },
];

// Mock categories
export const mockCategories = [
  {
    id: 1,
    name: "Streaming Services",
    slug: "streaming-services",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400",
  },
  {
    id: 2,
    name: "Gaming & Social",
    slug: "gaming-social",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400",
  },
  {
    id: 3,
    name: "Design & Productivity",
    slug: "design-productivity",
    image: "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400",
  },
];

// Mock suppliers
export const mockSuppliers = [
  {
    id: 1,
    name: "Digital Entertainment Co.",
  },
  {
    id: 2,
    name: "Gaming Services Ltd.",
  },
  {
    id: 3,
    name: "Creative Tools Inc.",
  },
];

// Featured products for homepage
export const featuredProducts = mockProducts.slice(0, 4);

// Sale products (products with sale prices)
export const saleProducts = mockProducts.filter((product) =>
  product.properties.some((prop) => prop.salePrice !== null)
);

// Products under specific price point
export const productsUnder20 = mockProducts.filter((product) => product.lowestPrice < 20);
